#!/usr/bin/env bash

set -e

if uname -a|grep -q microsoft; then
CONFIG="config/wslinstall.conf.yaml"
elif uname -a|grep -q Linux; then
CONFIG="config/linuxinstall.conf.yaml"
else
CONFIG="config/install.conf.yaml"
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
