- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.custom.vim: vim/custom.vim
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh: oh-my-zsh
    ~/.zsh: zsh
    ~/.gitconfig: gitconfig

- shell:
  - [git submodule update --init --recursive, Installing submodules]
