- defaults:
    link:
      relink: true
      create: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.vim: vim
    ~/.vimrc: vim/vimrc
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh: oh-my-zsh
    ~/.zsh/custom: zsh/custom
    ~/.gitconfig: gitconfig
    ~/.global_extra_conf.py: global_extra_conf.py

- shell:
  - [git submodule update --init --recursive]
  - [git submodule update --init --remote]
