- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux/linuxtmux.conf
    ~/.vim: vim
    ~/.vimrc: vim/vimrc
    ~/.zshrc: zsh/linuxzshrc
    ~/.oh-my-zsh: oh-my-zsh
    ~/.zshcustom: zsh/custom
    ~/.gitconfig: gitconfig

- shell:
  - [git submodule update --init --recursive, Installing submodules]
